### ISSUE TITLE
Sequence generation

### ISSUE THREAD

**Issue by davidchall** [davidchall/bignum#14]
Should provide a `seq()` method.

**Comment by DavisVaughan** [comment]
Just randomly stumbled across this issue. Completely custom seq methods are a bit hard to get right because of all the complex interactions of the arguments. If you want to copy mine from clock and just replace the guts with bignum generation then that's fine by me. Just thought id offer since this outline is something I wish already existed.

https://github.com/r-lib/clock/blob/2cda5741d2e6a92adc9a1bfbc85cdf6125f6dba3/R/duration.R#L613-L733
https://github.com/r-lib/clock/blob/2cda5741d2e6a92adc9a1bfbc85cdf6125f6dba3/src/duration.cpp#L1229-L1469

**Comment by davidchall** [comment]
Wow! Thank you so much - this will be a huge time-saver! 👍

**Comment by davidchall** [comment]
@DavisVaughan - Would it make sense if {vctrs} implements the `seq()` generic in terms of 3 new generics: `seq_to_by()`, `seq_to_lo()` and `seq_by_lo()`? (perhaps with `vec_` prefixes?)
