### ISSUE TITLE
Failure with dev waldo

### ISSUE THREAD

**Issue by hadley** [davidchall/bignum#44]
waldo now (correctly) differentiates `NA` and `NaN` so two bignum tests fail:

```
Failure (test-vctrs-math.R:136:3): math returning float works
suppressWarnings(as.double(fun(biginteger(x), ...))) (`actual`) not equal to suppressWarnings(fun(x, ...)) (`expected`).

  `actual`: 0.4227843350984671 0.9227843350984671 NA  NA
`expected`: 0.4227843350984675 0.9227843350984675 NA NaN
Backtrace:
 1. bignum (local) check_math(x, digamma)
      at test-vctrs-math.R:136:2
 2. testthat::expect_equal(...)
      at test-vctrs-math.R:99:4

Failure (test-vctrs-math.R:136:3): math returning float works
suppressWarnings(as.double(fun(bigfloat(x), ...))) (`actual`) not equal to suppressWarnings(fun(x, ...)) (`expected`).

  `actual`: 0.4227843350984671 0.9227843350984671 NA  NA
`expected`: 0.4227843350984675 0.9227843350984675 NA NaN
Backtrace:
 1. bignum (local) check_math(x, digamma)
      at test-vctrs-math.R:136:2
 2. testthat::expect_equal(...)
      at test-vctrs-math.R:103:4
```

I didn't see an obvious way to fix this in just the tests, suggesting that this is revealing a real difference in behaviour that you might need to look into.

**Comment by davidchall** [comment]
Thanks for the warning, @hadley. I got back from traveling so I can investigate this now.

**Comment by davidchall** [comment]
The root cause is that `boost::math::digamma(-1)` raises an error, which bignum catches and converts to NA. In contrast, R returns NaN. The unit test compares the two values and finds a difference (since waldo 0.5.0).

I think the correct approach is to pass an [error handling policy](https://www.boost.org/doc/libs/1_53_0/libs/math/doc/sf_and_dist/html/math_toolkit/policy/pol_ref/error_handling_policies.html) as a second argument to `boost::math::digamma()`. This might need some effort to decide the correct policy and align other edge cases with R (including other operations).

In the short-term, I'll adjust the unit test to avoid encountering this NaN vs NA difference. It's a fairly minor issue, but is causing CRAN check failures.
